[workspace]
members = [
    "crates/veil-core",
    "crates/veil-cli",
    "crates/veil-config",
    "crates/veil-server",
    "crates/veil-guardian",
]

resolver = "2"

[profile.bench]
opt-level = 3
debug = 0
lto = "thin"
codegen-units = 1

