[core]
ignore = [
    "flake.lock",
    "Cargo.lock",
    "tests/",
    "target/",
    "dist/",
    ".git/",
    "node_modules/",
    ".direnv/",
    "CHANGELOG.md",
    "ROADMAP.md",
    "examples/",
    "dev/",
    "schemas/",
    "crates/veil/rules_ja/default/",
    "test_summary.html"
]

[rules."pii.heuristic.number_like.keyword"]
enabled = false
