[package]
name = "veil-core"
version = "0.2.1"
edition = "2021"

[dependencies]
regex = "1.10.4"
thiserror = "1.0.61"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rayon = "1.10"
ignore = "0.4"
veil-config = { path = "../veil-config" }
