[package]
name = "veil-config"
version = "0.10.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
thiserror = "1.0.61"
anyhow = "1.0.86"
regex = "1.12.2"
